---
# tasks file for gpu
- name:  apt update
  ansible.builtin.import_tasks: apt_update.yml 
 
- name: nvidia update
  ansible.builtin.import_tasks: nvidia_update.yml

- name: Install the container toolkit
  ansible.builtin.import_tasks: nvidia_ctoolkit.yml
